name: healthcare-api-to-ci-cd-pipeline-builder
on:
  push:
    branches:
    - main
jobs:
  healthcare-api-to-ci-cd-pipeline-builder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup docker
      uses: docker/setup-buildx-action@v1

    - name: Login into dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.dockerhub_username}}
        password: ${{secrets.dockerhub_password}}

    - name: Build + Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: prathameshvarhadpande/healthcare-api-to-ci-cd-pipeline-builder:latest